# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('value_x', models.FloatField()),
                ('value_y', models.FloatField()),
            ],
        ),
    ]
